### ISSUE TITLE
kore-exec --search --pattern not working correctly

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3518] opened 2023-02-23 18:06 UTC
[searchpattern.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10816813/searchpattern.tar.gz)

I would expect this execution to return a single substitution, but instead it returns bottom.

**Comment by alexd1971** [comment] 2023-02-27 07:36
@dwightguth, to be able to reproduce the issue with locally build kore-exec I need to `kompile` original k-file. Otherwise I get the following error:
```
kore-exec: [88344] Error (ErrorParse):
    The definition was serialized with a different version of kore-exec. Re-run kompile with the current executable.
```

**Comment by dwightguth** [comment] 2023-03-06 18:44
Any update on this issue? This is the one that is blocking my ability to convert the PL tutorial to the Haskell backend.

**Comment by alexd1971** [comment] 2023-03-07 06:45
After fixing #3523 I returned to the task. And currently I'm investigating the reason of the problem. Since the task solution is urgent, I probably need help of some one more experienced in domain logic than me.

**Comment by ana-pantilie** [comment] 2023-03-20 12:56
Fixed by https://github.com/runtimeverification/haskell-backend/pull/3549

**Closed by ana-pantilie** 2023-03-20 12:56 UTC
Labels: bug
