### ISSUE TITLE
Ceil simplification could be lazy

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2698] opened 2021-06-24 19:03 UTC
At present, the child terms of predicates are always simplified before the predicate itself; for example, in the predicate `\ceil(T)`, `T` is always fully simplified before trying to evaluate its `\ceil`. That makes sense for most of the predicates, but it may be wasteful for `\ceil`. Consider a pattern such as `\ceil(f(X₁, X₂, ...))` where `f(...)` is a total function that is expensive to compute; we know that this definedness condition is `\ceil(X₁) ∧ \ceil(X₂) ∧ ...` without evaluating `f` because it is total, but the backend will evaluate `f` anyway. Likewise, the values in the key-value pairs of a Map will be evaluated when evaluating the definedness of the Map, even though the actual values are irrelevant. We should consider attempting to simplify `\ceil` before simplifying its children, when that is possible.

**Comment by ana-pantilie** [comment] 2022-09-13 16:33
Duplicate of #3126

**Closed** 2022-09-14 09:45 UTC
Labels: feature, performance
