### ISSUE TITLE
No split on KEVM JUMPI

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/haskell-backend#2997] opened 2022-03-11 09:39 UTC
Steps to reproduce:
```
cd evm-semantics
make tests/specs/benchmarks/ecrecoverloop00-sig1-invalid-spec.k.prove
```

Expected behavior: should pass

Actual behavior: Execution gets stuck with the following content of `k` cell:
```
JUMPI 559 bool2Word ( 0 <Int maxUInt160 &Int #asWord ( #range ( b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01`" [ 128 := #buf ( 32 , SIGV0:Int ) ++ #buf ( 32 , SIGV1:Int ) ] [ 192 := #buf ( 32 , SIGR0:Int ) ++ #buf ( 32 , SIGR1:Int ) ] [ 256 := #buf ( 32 , SIGS0:Int ) ++ #buf ( 32 , SIGS1:Int ) ] [ 320 := b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ] [ 320 := #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) [ 0 .. minInt ( 32 , #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) ) ] ] , 320 , 32 ) ) )
```

It should split on `JUMPI` insteadm, based on these rules:

```
    rule <k> JUMPI _DEST I => . ... </k>
      requires I ==Int 0

    rule <k> JUMPI  DEST I => JUMP DEST ... </k>
      requires I =/=Int 0
```

**Comment by andreiburdusa** [comment] 2022-03-11 10:32
I already investigated this some time ago, but couldn't solve it. From what I see, the proof does branch, like this
![Screenshot from 2022-03-11 12-09-51](https://user-images.githubusercontent.com/53746396/157847506-9a07d4ce-c137-4452-ad29-42239d9e4683.png)

Axiom 42 is
```
    rule <k> JUMPI _DEST I => . ... </k>
      requires I ==Int 0
```
Axiom 43 is
```
    rule <k> JUMPI  DEST I => JUMP DEST ... </k>
      requires I =/=Int 0
```
The configuration on node `1763` contains the following
```
...
#And
  #Not ( {
    true
  #Equals
    0 <Int maxUInt160 &Int #asWord ( #range ( b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01`" [ 128 := #buf ( 32 , SIGV0 ) ++ #buf ( 32 , SIGV1 ) ] [ 192 := #buf ( 32 , SIGR0 ) ++ #buf ( 32 , SIGR1 ) ] [ 256 := #buf ( 32 , SIGS0 ) ++ #buf ( 32 , SIGS1 ) ] [ 320 := b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ] [ 320 := #ecrec ( #buf ( 32 , HASH ) , #buf ( 32 , SIGV0 ) , #buf ( 32 , SIGR0 ) , #buf ( 32 , SIGS0 ) ) [ 0 .. minInt ( 32 , #sizeByteArray ( #ecrec ( #buf ( 32 , HASH ) , #buf ( 32 , SIGV0 ) , #buf ( 32 , SIGR0 ) , #buf ( 32 , SIGS0 ) ) ) ) ] ] , 320 , 32 ) )
  } )
#And
  #Not ( {
    true
  #Equals
    maxUInt160 &Int #asWord ( #range ( b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01`" [ 128 := #buf ( 32 , SIGV0 ) ++ #buf ( 32 , SIGV1 ) ] [ 192 := #buf ( 32 , SIGR0 ) ++ #buf ( 32 , SIGR1 ) ] [ 256 := #buf ( 32 , SIGS0 ) ++ #buf ( 32 , SIGS1 ) ] [ 320 := b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ] [ 320 := #ecrec ( #buf ( 32 , HASH ) , #buf ( 32 , SIGV0 ) , #buf ( 32 , SIGR0 ) , #buf ( 32 , SIGS0 ) ) [ 0 .. minInt ( 32 , #sizeByteArray ( #ecrec ( #buf ( 32 , HASH ) , #buf ( 32 , SIGV0 ) , #buf ( 32 , SIGR0 ) , #buf ( 32 , SIGS0 ) ) ) ) ] ] , 320 , 32 ) ) <=Int 0
  } )
#And
...
```
which basically says that `maxUInt160 &Int ...` is both <= and > 0. 

I think the backend gets stuck because it can't detect that its branch is infeasible.

**Comment by ana-pantilie** [comment] 2022-03-11 10:55
@andreiburdusa So is this a problem in the Haskell backend or is it a problem with KEVM in the sense that it's missing some simplification rules?

**Comment by andreiburdusa** [comment] 2022-03-11 11:08
I think it's a problem with the backend because some rules that me and Everett expected to make the proof advance didn't help

**Comment by ana-pantilie** [comment] 2022-04-14 12:07
Most likely an issue with sending the condition to SMT. Possibly a duplicate of https://github.com/runtimeverification/haskell-backend/issues/3032

**Comment by ehildenb** [comment] 2022-09-22 15:26
Test is still failing, needs reproducing then: https://github.com/runtimeverification/evm-semantics/blob/master/tests/failing-symbolic.haskell#L1

**Comment by goodlyrottenapple** [comment] 2022-09-29 11:29
try to see if a simplified expression

```
#And
  #Not ( {
    true
  #Equals
    0 <Int foo
  } )
#And
  #Not ( {
    true
  #Equals
    foo <=Int 0
  } )
```
gets automatically simplified

**Comment by jinxinglim** [comment] 2022-09-30 05:47
Hi all, I have made a pull request (https://github.com/runtimeverification/evm-semantics/pull/1408) that address this issue. Basically, I added the following two rules and the proof of `ecrecoverloop00-sig1-spec.k` succeeded:
```k
rule A  <Int B => #Not ( { true #Equals B <=Int A } ) [simplification]
rule A <=Int B => #Not ( { true #Equals B  <Int A } ) [simplification]
```

I also documented my many other attempts on the issue but only this one works as of now.

**Comment by goodlyrottenapple** [comment] 2022-09-30 12:18
Confirmed that the SMT solver can discharge this goal when simple enough, so likely failing to translate the condition in the actual test. The two rules above seem like a good solution as we don't want to rely on the SMT solver magic when a concrete simplification rule works.

**Closed by goodlyrottenapple** 2022-09-30 12:18 UTC
Labels: bug, smt, needs-reproducing

**Comment by jinxinglim** [comment] 2022-10-18 08:36
Hi all. I just want to update the attempts I have made and am asking for suggestions to debug this proof.

#### Attempt 1
As pointed out in https://github.com/runtimeverification/haskell-backend/issues/3302, although the following rules allow the proof of `tests/specs/benchmarks/ecrecoverloop00-sig1-invalid-spec.k` to pass, it causes some other proof/s to fail and are considered as invalid due to the reasons provided by @virgil-serbanuta:
```k
rule A  <Int B => #Not ( { true #Equals B <=Int A } ) [simplification]
rule A <=Int B => #Not ( { true #Equals B  <Int A } ) [simplification]
```

#### Attempt 2
As discussed in https://github.com/runtimeverification/evm-semantics/pull/1408, following the specification of `tests/specs/benchmarks/ecrecoverloop02-sig1-invalid-spec.k`, a (successful) proof similar to `tests/specs/benchmarks/ecrecoverloop00-sig1-invalid-spec.k`, I added the following new side condition in the specification file and the proof succeeded:
```k
notBool #ecrecEmpty( #bufStrict(32, HASH), #bufStrict(32, SIGV0), #bufStrict(32, SIGR0), #bufStrict(32, SIGS0) )
```
However, as pointed out by @ehildenb, I was making the proof statement less general than it is intended to be with this change by constraining the initial state more. The point of this proof is to show that **"we will always fail if the 1-th signature is invalid, regardless of whether the 0-th signature is valid or not"**. 

Thus, this means that we need to update the following:
1. remove the side condition `notBool #ecrecEmpty( #bufStrict(32, HASH), #bufStrict(32, SIGV0), #bufStrict(32, SIGR0), #bufStrict(32, SIGS0) )` from `tests/specs/benchmarks/ecrecoverloop02-sig1-invalid-spec.k`, and
2. add a lemma such that both `tests/specs/benchmarks/ecrecoverloop00-sig1-invalid-spec.k` and `tests/specs/benchmarks/ecrecoverloop02-sig1-invalid-spec.k` proofs can succeed without the above side condition.

#### Attempt 3
I tried to add the following rule in `tests/specs/benchmarks/verification.k`:
```k
rule #Not ( { true #Equals B <Int A } ) => { true #Equals A <=Int B } [simplification]
```
to see if we can change from:
```k
#And
  #Not ( {
    true
  #Equals
    0 <Int maxUInt160 &Int #asWord ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ++ #range ( b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01`" [ 128 := #buf ( 32 , SIGV0:Int ) ++ #buf ( 32 , SIGV1:Int ) ] [ 192 := #buf ( 32 , SIGR0:Int ) ++ #buf ( 32 , SIGR1:Int ) ] [ 256 := #buf ( 32 , SIGS0:Int ) ++ #buf ( 32 , SIGS1:Int ) ] [ 320 := b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ] , #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) +Int 320 , 32 -Int #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) ) )
  } )
#And
  #Not ( {
    true
  #Equals
    maxUInt160 &Int #asWord ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ++ #range ( b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01`" [ 128 := #buf ( 32 , SIGV0:Int ) ++ #buf ( 32 , SIGV1:Int ) ] [ 192 := #buf ( 32 , SIGR0:Int ) ++ #buf ( 32 , SIGR1:Int ) ] [ 256 := #buf ( 32 , SIGS0:Int ) ++ #buf ( 32 , SIGS1:Int ) ] [ 320 := b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ] , #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) +Int 320 , 32 -Int #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) ) ) <=Int 0
  } )
```
to:
```k
#And
  {
    true
  #Equals
    maxUInt160 &Int #asWord ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ++ #range ( b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01`" [ 128 := #buf ( 32 , SIGV0:Int ) ++ #buf ( 32 , SIGV1:Int ) ] [ 192 := #buf ( 32 , SIGR0:Int ) ++ #buf ( 32 , SIGR1:Int ) ] [ 256 := #buf ( 32 , SIGS0:Int ) ++ #buf ( 32 , SIGS1:Int ) ] [ 320 := b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ] , #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) +Int 320 , 32 -Int #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) ) ) <=Int 0
  }
#And
  #Not ( {
    true
  #Equals
    maxUInt160 &Int #asWord ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ++ #range ( b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01`" [ 128 := #buf ( 32 , SIGV0:Int ) ++ #buf ( 32 , SIGV1:Int ) ] [ 192 := #buf ( 32 , SIGR0:Int ) ++ #buf ( 32 , SIGR1:Int ) ] [ 256 := #buf ( 32 , SIGS0:Int ) ++ #buf ( 32 , SIGS1:Int ) ] [ 320 := b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" ] , #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) +Int 320 , 32 -Int #sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) ) ) ) <=Int 0
  } )
```
in hope that they will cancel out each other.

But it seems like the new rule was not applied at all, and thus no change has occurred. My guess is that in order for the new rule to apply, we need the variables `B` and `A` are of type `Int` but as at current state, it is not known that `maxUInt160 &Int #asWord ( ... )` is of type `Int`. The following is the bug-report:

[kevm-bug-ecrecoverloop00-sig1-invalid.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9808276/kevm-bug-ecrecoverloop00-sig1-invalid.tar.gz)

#### Moving forward
I am currently trying to figure out what rule to be included so that both `tests/specs/benchmarks/ecrecoverloop00-sig1-invalid-spec.k` and `tests/specs/benchmarks/ecrecoverloop02-sig1-invalid-spec.k` proofs can succeed without the side condition of `notBool #ecrecEmpty( #bufStrict(32, HASH), #bufStrict(32, SIGV0), #bufStrict(32, SIGR0), #bufStrict(32, SIGS0) )`. 

#### Questions
1. Does attempt 2 provide any insight to how we can approach this issue? It seems like when the side condition `notBool #ecrecEmpty( #bufStrict(32, HASH), #bufStrict(32, SIGV0), #bufStrict(32, SIGR0), #bufStrict(32, SIGS0) )` is given, the value of `#sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) )` seems to be evaluated to `32` through the following rules found in `tests/specs/benchmarks/verification.k`:
```k
rule #sizeByteArray(#ecrec(HASH, SIGV, SIGR, SIGS)) => 32 requires notBool #ecrecEmpty(HASH, SIGV, SIGR, SIGS) [simplification]
rule #sizeByteArray(#ecrec(HASH, SIGV, SIGR, SIGS)) => 0  requires         #ecrecEmpty(HASH, SIGV, SIGR, SIGS) [simplification]
```
and as a result, the prover knows exactly which path to take and the proof succeeds. Without any condition on `#ecrecEmpty( #bufStrict(32, HASH), #bufStrict(32, SIGV0), #bufStrict(32, SIGR0), #bufStrict(32, SIGS0) )`, it seems like there is no value for `#sizeByteArray ( #ecrec ( #buf ( 32 , HASH:Int ) , #buf ( 32 , SIGV0:Int ) , #buf ( 32 , SIGR0:Int ) , #buf ( 32 , SIGS0:Int ) ) )` to rewrite to.

2. Or should I just focus on thinking of rewrite rules that solve the problem that `A <Int B` and `A <=Int B` cannot happen at the same time? I have tried many attempts on this but nothing seems to work. It could be the problem that `maxUInt160 &Int #asWord ( ... )` cannot be evaluated as type `Int` at the current state/node.

#### Suggestions
If anyone has any idea or suggestion on what kind of rules I should implement, please feel free to let me know so that I can test them out and hopefully debug this proof. Thank you.

**Comment by fiedlr** [comment] 2022-10-19 10:18
Just a few ideas:

The situation is very analogous to my attemps for `collectToken-spec.k`. I can also make the proof pass with a stronger side condition, the problem is that branches for failing asserts are not pruned. It is likely because `chop` cannot be simplified further for some reason in the condition for the given assert.

Some of the simplifications in `verification.k` are defined for `chop` but they do not apply, and the test also contains many of these "ghost" terms that do not rewrite to anything. I'm guessing that the reason they are there is to make some of the simplifications in `verification.k` enabled only for this test, but that's only my guess and they might make things difficult for the prover.

**Comment by ehildenb** [comment] 2022-11-17 16:53
This is blocking removing the Java backend from KEVM, because two proofs `bihu/collectToken-spec.k` and `benchmarkes/ecrecoverloop00-sig1-invalid-spec.k` are relying on this functionality, and currently only pass on the Java backend.

**Comment by fiedlr** [comment] 2022-11-23 10:29
@ehildenb `bihu/collectToken-spec.k` seems to fail due to the same "`<, >=`" problem as the one mentioned above. The following side condition:
```
{ true #Equals NOW:Int -Int START:Int /Int 31536000 <=Int 0 }
#And { true #Equals 0 <Int NOW:Int -Int START:Int }
```
isn't detected to be false when running `bihu/collectToken-spec.k`, leading to exploration of infeasible branches, which eventually fail on false asserts.

However, if one extracts the problematic node to a functional test with almost the same side condition, the prover *does detect* the side condition to be false (we can prove `true => false` for example).

A minimal example and more details can be found at https://github.com/runtimeverification/evm-semantics/pull/1425

**Comment by ana-pantilie** [comment] 2023-01-10 14:43
Could be related to https://github.com/runtimeverification/haskell-backend/issues/3409

**Comment by Sereja313** [comment] 2023-02-09 16:12
@ana-pantilie I managed to reproduce this error.
backend version:
```
Kore version 0.60.0.0
Git:
  revision:	74bc7a963a825d0f0f034b5d3412dc59448e51bb (dirty)
  branch:	master
  last commit:	Tue Feb 7 05:02:49 2023 -0700
```
