### ISSUE TITLE
Skip definedness checks by analyzing definition

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3136] opened 2022-07-07 15:22 UTC
KEVM has the property that it "preserves definedness".

We should be able to take advantage of that to have to _only_ check that the initial configuration is defined, and very rarely (if ever) after that check it again.

Maybe we can analyze the definition ahead of time, and mark certain rules as "definedness preserving"? That way after those rules apply we don't have to check definedness.

**Comment by ana-pantilie** [comment] 2022-08-09 11:09
Duplicate of [#3175](https://github.com/runtimeverification/haskell-backend/issues/3175)

**Closed by ana-pantilie** 2022-08-09 11:09 UTC
