### ISSUE TITLE
Improve performance of symbolically executing C semantics

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/haskell-backend#3182] opened 2022-08-02 17:00 UTC
I am working on getting symbolic execution working for the C semantics, but progress is very slow because symbolic execution is incredibly slow, to the point of taking hours on even incredibly basic C programs.

I am sharing two C programs for reference in the attachments, in the form of bug reports containing the definition.kore and initial kore configurations. The first is simply `int main() { return 0; }` and takes roughly 10 minutes to execute, despite only having roughly 100 steps of execution. The second is slightly more complicated:

```
#include <rvmatch/symbolic.h>

int main() {

  int x;
  if (symbolic(int) >= 2)
    x = 1;

  x; // maybe uninitialized

  return 0;
}
```

`symbolic` is a macro which is implemented in such a way that `symbolic(int)` returns an rvalue of type `int` whose value is a variable. This program is also highly simple, but it will run for multiple days without finishing. For comparison, both programs run on the llvm backend in less than a second.

Even though I shared the bug reports with `definition.kore`, I strongly suggest running `kore-exec --serialize` and using the serialized definition before actually profiling them. The placement of the kore definition and other initial information into a compact region has significant impact on garbage collection throughput beyond simply the additional ~40s of bootup time it takes to construct the initial definition from scratch.

Any insight into where time is being spent would be valuable, as I am having trouble figuring out how to optimize these programs further.

[smoke.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9244273/smoke.tar.gz)
[maybe-uninitialized.tar.gz](https://github.com/runtimeverification/haskell-backend/files/9244274/maybe-uninitialized.tar.gz)

**Comment by jberthold** [comment] 2022-08-03 06:36
Some leads have already been identified for why the programs are so slow, see the related Slack discussion.
Key postings: 
* [Program takes 30 seconds with `Ceil` simplification forcefuly disabled](https://runtimeverification.slack.com/archives/CC360GUTG/p1659467777654899).  
  Issue #3136 was created to address this. 
* A possible short term solution is to have [a front-end flag that omits all rules relating to `Ceil` simplification from `definitions.kore`](https://runtimeverification.slack.com/archives/CC360GUTG/p1659472275527229).
  https://github.com/runtimeverification/k/pull/2768 implements this as a proposal.
* [`MultiAnd.filterAnd` appears to be another bottleneck](https://runtimeverification.slack.com/archives/CC360GUTG/p1659474971053329), This is being addressed in #3099

**Comment by dwightguth** [comment] 2022-08-03 09:03
Note: there are two programs here. I have not tested the second one with ceil simplification fully disabled; but the short term fix pr I created only optimizes the second program up to about 100 steps; after that, each step starts taking over a minute, even with no ceil simplification axioms.

**Comment by ehildenb** [comment] 2022-08-03 16:05
Also note that the flag `--disable-ceil-simplification-rules` does not work for any non-trivial proofs, so it's not a long term fix and I don't think is even worth merging actually. It's good to have for experiments.

As far as I understand it, the problem is this (@dwightguth please confirm):

1. Simplification is called on some term, which triggers the equation application.
2. Equation application triggers a call to the Ceil simplifier.
3. The Ceil simplifier searches for user-supplied rules with `#Ceil` at the top, and tries to apply them, _using the same equation applicaiton procedure as (1)_. It's this recursive call to equation application procedure that is slow, because it can retrigger this entire process.

Maybe a better fix is to make a specific "Ceil equation application procedure", which does not have the full generality of the normal equation application. In particular, it should never recurse back into the ceil simplifier, it should just do one level of applying the user-supplied `#Ceil` equations and then quit. This should allow users to supply Ceil rules (needed for any non-trivial proofs), but stop the bad performance case here.

**Comment by jberthold** [comment] 2022-08-05 07:44
As discussed, profiles for the programs here show that much time is spent in `hashWithSalt @ TermLike`.
An initial experiment with a `SimplifierCache` that used a simple (`Ord`-based) `Map` still showed `hashWithSalt @ TermLike` as the biggest eater in the profile (`smoke` program), most likely due to `SideCondition` whose contents could not be converted easily to use `Map/Set` instead of `HashMap/HashSet`.
Following some discussions on slack and in person, I am attempting to cache hashes for all `TermLike` data to avoid recomputation, in https://github.com/runtimeverification/haskell-backend/compare/jb/caching-termlike-hashes (WIP, failing tests at the moment)

**Comment by ehildenb** [comment] 2022-08-07 05:58
Are we able to delay simplifying the generated `#Ceil` conditions, instead of immediately discharging them? Could we store them in a list, and then cycle over them all afterwards one at a time separately? Then we could have a simpler rewriter used for that last pass of simplification of the Ceil conditions, which would probably be enough for a lot of cases.

**Closed** 2023-02-02 18:45 UTC
Labels: performance
