### ISSUE TITLE
Booster: More flexible rewrite rule indexing 

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/haskell-backend#3874] opened 2024-05-16 01:10 UTC
The rule index implementation is currently a simple hard-wired search for a cell called `k` containing a non-empty `kseq` ). 

We can obviously do better by 
* making this cell (`k` by default) configurable for the server
* adding a way to consider more than one cell for the index. This is important for layered semantics. As an example: for the MX backend, we would need `instrs`, `k`, and  `commands`). This alternative is still an over-approximation but an improvement over picking just one of these three important cells.

Computing this automatically as suggested in #3769 would be a great addition to booster, and can happen at load time or at compile time (adding metadata to the definition). 
As a first step to address current issues, we can quickly implement the manual mode described above.

**Comment by goodlyrottenapple** [comment] 2024-05-21 14:56
Duplicate of [#3769](https://github.com/runtimeverification/haskell-backend/issues/3769)

**Closed** 2024-05-27 10:55 UTC
