### ISSUE TITLE
`chop` function isn't evaluated by `get-model` in RPC

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/haskell-backend#3616] opened 2023-06-28 12:03 UTC
Related: runtimeverification/evm-semantics#1927, runtimeverification/evm-semantics#1700, runtimeverification/evm-semantics#1716 

runtimeverification/evm-semantics#1927 adds showing counterexamples (i.e., concrete assignments to variables) for failed Foundry proofs. However, `get-model` doesn't produce a correct assignment in the presence of the `chop` function in predicates.

For example, the asserted expression in the following test
```
    function testUint(uint v) public pure {
        assert(v < 4);
    }
```
is translated into the 
```true #Equals 0 <=Int CALLER_ID:Int``` constraint, and the assignment in the counterexample is reported correctly:
```
VV0_v_114b9705: {... 'token': '4'...}
```

Changing the asserted expression to 
```
assert(v != 4)
``` 
translates into the predicate 
```
0 #Equals chop ( ( 4 -Int VV0_v_114b9705:Int ) )
```
 and the counterexample now reports the assignment `v = 0` instead of the expected `v = 4`:
```
VV0_v_114b9705: {... 'token': '0' ... }
```

Calling `simplify` on the analyzed failed node's `CTerm` prior to the `get-model` request doesn't evaluate the call to `chop`.

The `get-model`'s request and response information are available [is this gist](https://gist.github.com/palinatolmach/da476107bc1651312bc68c7c1d05cf59).

As suggested by @jberthold, the issue might be caused by the SMT solver evaluating `chop` as an uninterpreted function, while it is a known function on Int corresponding to "integer modulo 2^256". It, therefore, might be fixed by providing the `smt-hook` (e.g., `smt-hook((mod runtimeverification/evm-semantics#1 (^ 2 256)))`) for `chop` defined in [word.md](https://github.com/runtimeverification/evm-semantics/blob/ab2e2bf1deda7532457aead670e2582ad6397503/include/kframework/word.md?plain=1#L343).

To reproduce, please use
- [`foundry-counterexamples`](https://github.com/runtimeverification/evm-semantics/tree/foundry-counterexamples) branch of `evm-semantics`, using the `pyk` built from
- [`cterm-get-model`](https://github.com/runtimeverification/pyk/tree/cterm-get-model) branch of pyk
- [`foundry-test`](https://github.com/palinatolmach/foundry-test) (or any other Foundry project).

**Comment by ehildenb** [comment] 2023-07-01 16:06
I've transferred this issue to the haskell backend repo, as it seems to be an issue there.

We should:

- Make a new K definition here called `smt.k`, which contains this example of an `smt-lemma` marked as `concrete`.
- Add a testing harness for `smt.k` which demonstrates the issue similar to the one here: https://github.com/runtimeverification/pyk/pull/519/files#diff-98e3d7d2765cb42cfbe8ec6cdb0cd0156ce6a50a727af90e1b5587f8d3a75f4dR719.
- Produce the bug report associated with that test by uncommenting this line https://github.com/runtimeverification/pyk/blob/49d861944bad260be137f68f4adc37b360e25771/src/pyk/testing/_kompiler.py#L59, and then running the desired test.
- Upload the created test tarball here.

Note that I am not sure if this bug report generation funcitonality works as expected still, after this change by @tothtamas28 , https://github.com/runtimeverification/pyk/pull/454. If not, let's figure it out on Slack how to make the new bug report.

**Comment by jberthold** [comment] 2023-07-03 06:49
As it turns out, the `concrete` attribute is irrelevant for whether the SMT solver gets this lemma.
The problem is that for a function equation, the kore encoding adds artificial `\in(dummyVar, actualArgument)` preconditions to ensure definedness of the arguments, see [the related design document](https://github.com/runtimeverification/haskell-backend/blob/master/design-decisions/2020-05-02-function-rules.md). 

In this case, the rule `rule chop(I) => I modInt ...value of 2 ^ 256...` becomes the following in kore (`\top` occurrences elided):
```
/* Spa */ \implies{R}(
  /* Spa */ \in{SortInt{}, R}(
    /* T Fn D Sfa */ X0:SortInt{},
    /* T Fn D Sfa */ VarI:SortInt{}
  ),
  /* Spa */ \equals{SortInt{}, R}(
    /* T Fn D Spa */ Lblchop'LParUndsRParUnds'SMT'Unds'Int'Unds'Int{}(/* T Fn D Sfa */ X0:SortInt{} ),
    /* Fn Spa */ Lbl'Unds'modInt'Unds'{}(
      /* T Fn D Sfa */ VarI:SortInt{},
      /* T Fn D Sfa Cl */ \dv{SortInt{}}("...value of 2 ^ 256...")
    )
  )
)
```
The presence of this `\in` predicate prevents the lemma from being translated for SMT. 
We can probably un-do the `\in` encoding specifically for SMT lemma translation (we do a similar thing in booster) but should think about the implications of ignoring undefined arguments.

**Comment by palinatolmach** [comment] 2023-07-03 12:35
The draft pull request https://github.com/runtimeverification/pyk/pull/520 adds two tests for the `get-model` endpoint that involve `chop` function defined as:
```
  syntax Int ::= chop ( Int )           [function, total, klabel(chop), smtlib(chop)]
  syntax Int ::= "pow256"               [alias] /* 2 ^Int 256 */

  rule pow256 => 115792089237316195423570985008687907853269984665640564039457584007913129639936
  rule chop ( I:Int ) => I modInt pow256 [concrete, smt-lemma]
```

The first test `sat-chop-single-int` shows that the variable substitution returned for `chop(x) == x && x == 1` is correct: `x = 1`. The second, failing, test `sat-chop-sub-ints` shows that the reported substitution (`x = 0`) is incorrect for an expression that involves subtraction: `chop(1 - x) == 0`.

The bug report for the failing test is attached: [bug-report.zip](https://github.com/runtimeverification/haskell-backend/files/11936765/bug-report.zip).

**Closed** 2023-07-04 15:18 UTC
