### ISSUE TITLE
Optimism proof failing with SMT error

### ISSUE THREAD

**Issue by ana-pantilie** [runtimeverification/haskell-backend#3400] opened 2022-12-08 09:41 UTC
### From @PetarMax 

I have a very strange problem happening. If I turn on the simplification:
```
    // used for bitwise-AND-inequality-2
    rule (X &Int Y) <=Int Y => true
      requires 0 <=Int X
       andBool 0 <=Int Y
      [simplification, smt-lemma]
```
and try to run
``` kevm foundry-prove out --test Spec.test_depositTransaction_revert --reinit --no-minimize --verbose ```
kprove just fails on me when simplifying the starting node with:
```
INFO 2022-12-07 16:45:39,759 pyk.ktool.kprove - Running: kprove out/specs/simplify-init-c3a8f22232a3f1860a6a75edb6212d00e8f3178188f56b34b32e3afa2bc69080-spec.k --definition out/kompiled --spec-module SIMPLIFY-INIT-C3A8F22232A3F1860A6A75EDB6212D00E8F3178188F56B34B32E3AFA2BC69080-SPEC --output json --depth 0
Created bug report: kore-exec.tar.gz
[Error] Critical: Haskell Backend execution failed with code 1 and produced no
output.
INFO 2022-12-07 16:46:21,570 pyk.ktool.kprove - Completed: kprove out/specs/simplify-init-c3a8f22232a3f1860a6a75edb6212d00e8f3178188f56b34b32e3afa2bc69080-spec.k --definition out/kompiled --spec-module SIMPLIFY-INIT-C3A8F22232A3F1860A6A75EDB6212D00E8F3178188F56B34B32E3AFA2BC69080-SPEC --output json --depth 0
Traceback (most recent call last):
  File "/nix/store/93xs11xkccxrfbhi0smx0wb0w4qgvyhv-python3.9-kevm-pyk-0.1.0/bin/.kevm-pyk-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/93xs11xkccxrfbhi0smx0wb0w4qgvyhv-python3.9-kevm-pyk-0.1.0/lib/python3.9/site-packages/kevm_pyk/__main__.py", line 48, in main
    execute(**vars(args))
  File "/nix/store/93xs11xkccxrfbhi0smx0wb0w4qgvyhv-python3.9-kevm-pyk-0.1.0/lib/python3.9/site-packages/kevm_pyk/__main__.py", line 336, in exec_foundry_prove
    init_simplified = foundry.prove_claim(
  File "/nix/store/2mxxavz5b635nh57l9zlbl8gp7ilk856-python3.9-pyk-0.1.80/lib/python3.9/site-packages/pyk/ktool/kprove.py", line 256, in prove_claim
    return self.prove(
  File "/nix/store/2mxxavz5b635nh57l9zlbl8gp7ilk856-python3.9-pyk-0.1.80/lib/python3.9/site-packages/pyk/ktool/kprove.py", line 231, in prove
    raise RuntimeError('kprove failed!')
RuntimeError: kprove failed!
```
but if I don’t include the simplification, the proof continues into the simplification of the target node…
The error log in the bug report says
```
Failed to decide predicate:
    /* Sfa */
    \not{_}(
        /* Sfa */
        \equals{SortBool{}, _}(
            /* Fl Fn D Sfa Cl */ \dv{SortBool{}}("false"),
            /* Fl Fn D Sfa */
            Lbl'Unds'in'Unds'keys'LParUndsRParUnds'MAP'Unds'Bool'Unds'KItem'Unds'Map{}(
                /* Fl Fn D Sfa Cli */
                /* Inj: */ inj{SortInt{}, SortKItem{}}(
                    /* Fl Fn D Sfa Cl */
                    \dv{SortInt{}}("46308022326495007027972728677917914892729792999299745830475596687180801507328")
                ),
                /* Fl Fn D Sfa */ VarCHEATCODE'Unds'STORAGE:SortMap{}
            )
        )
    )
with side condition:
    /* D Sfa */ \top{_}()
SMT limit set at:
    1
```
and there is no mention of &Int in spec.kore. Any ideas?

Bug report: [kore-exec.tar.gz](https://github.com/runtimeverification/haskell-backend/files/10185966/kore-exec.tar.gz)
### Proposed investigation path
We need to figure out the relationship between adding that lemma and this error.

Try to find the following info:
- the callstack of the function which errors with ErrorDecidePredicateUnknown
- if the equation in question is attempted right before this error

**Comment by goodlyrottenapple** [comment] 2022-12-09 12:17
@PetarMax I've managed to minimise the smtlib script which causes Z3 to loop, namely:


```lisp

(declare-fun andInt (Int Int ) Int )
(assert (forall ((X Int ) ) (=> (= (<= 0 X ) true ) (= (< (andInt 281474976710655 X ) 281474976710656 ) true ) ) ) )
(assert (forall ((X Int ) ) (=> (= (<= 0 X ) true ) (= (< (andInt 255 X ) 256 ) true ) ) ) )
(assert (forall ((X Int ) ) (=> (= (<= 0 X ) true ) (= (< (andInt 1461501637330902918203684832716283019655932542975 X ) 1461501637330902918203684832716283019655932542976 ) true ) ) ) )
(assert (forall ((X Int ) (Y Int ) ) (=> (= (and (<= 0 X ) (<= 0 Y ) ) true ) (= (<= 0 (andInt X Y ) ) true ) ) ) )
(assert (forall ((X Int ) (Y Int ) ) (=> (= (and (<= 0 X ) (<= 0 Y ) ) true ) (<= (andInt X Y ) X ) ) ) )
(assert (forall ((X Int ) (Y Int ) ) (=> (= (and (<= 0 X ) (<= 0 Y ) ) true ) (<= (andInt X Y ) Y ) ) ) )


(check-sat )
```

weirdly, this works:

```lisp
(declare-fun andInt (Int Int ) Int )
(assert (forall ((X Int ) ) (=> (= (<= 0 X ) true ) (= (< (andInt 281474976710655 X ) 281474976710656 ) true ) ) ) )
(assert (forall ((X Int ) ) (=> (= (<= 0 X ) true ) (= (< (andInt 255 X ) 256 ) true ) ) ) )
(assert (forall ((X Int ) ) (=> (= (<= 0 X ) true ) (= (< (andInt 1461501637330902918203684832716283019655932542975 X ) 1461501637330902918203684832716283019655932542976 ) true ) ) ) )
(assert (forall ((X Int ) (Y Int ) ) (=> (= (and (<= 0 X ) (<= 0 Y ) ) true ) (= (<= 0 (andInt X Y ) ) true ) ) ) )
(assert (forall ((X Int ) (Y Int ) ) (=> (= (and (<= 0 X ) (<= 0 Y ) ) true ) (and (<= (andInt X Y ) X ) (<= (andInt X Y ) Y )) ) ) )

(check-sat )
```
 so ive tried replacing your original two rules:
 
 ```
 rule (X &Int Y) <=Int X => true
      requires 0 <=Int X
       andBool 0 <=Int Y
      [simplification, smt-lemma]
      
  rule (X &Int Y) <=Int Y => true
      requires 0 <=Int X
       andBool 0 <=Int Y
      [simplification, smt-lemma]
```

with a single one[^1]:

 ```
 
 rule (X &Int Y) <=Int X  #And (X &Int Y) <=Int Y => true
      requires 0 <=Int X
       andBool 0 <=Int Y
      [simplification, smt-lemma]
```


[^1]:this is probably not correct k syntax, as I modified the kore file:


in the kore file, the axiom now looks like this:
```
  axiom{R} \implies{R} (
    \equals{SortBool{},R}(
        Lbl'Unds'andBool'Unds'{}(Lbl'Unds-LT-Eqls'Int'Unds'{}(\dv{SortInt{}}("0"),VarX:SortInt{}),Lbl'Unds-LT-Eqls'Int'Unds'{}(\dv{SortInt{}}("0"),VarY:SortInt{})),
        \dv{SortBool{}}("true")),
    \and{R} (
        \equals{SortBool{},R} (
            Lbl'Unds-LT-Eqls'Int'Unds'{}(Lbl'UndsAnd-'Int'Unds'{}(VarX:SortInt{},VarY:SortInt{}),VarX:SortInt{}),
            \and{SortBool{}} (
            \dv{SortBool{}}("true"),
                \top{SortBool{}}())),
        \equals{SortBool{},R} (
            Lbl'Unds-LT-Eqls'Int'Unds'{}(Lbl'UndsAnd-'Int'Unds'{}(VarX:SortInt{},VarY:SortInt{}),VarY:SortInt{}),
            \and{SortBool{}} (
            \dv{SortBool{}}("true"),
                \top{SortBool{}}())) 
    )
    )
  [org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/Users/petarmax/Projects/RV/_audits_Ethereum-optimism_optimism/optimism_foundry/optimism-lemmas.k)"), org'Stop'kframework'Stop'definition'Stop'Production{}("syntax #RuleContent ::= #RuleBody \"requires\" Bool [klabel(#ruleRequires), symbol]"), org'Stop'kframework'Stop'attributes'Stop'Location{}("Location(77,10,79,25)"), simplification{}(""), UNIQUE'Unds'ID{}("fb6b0fd23915d4e80df6751b2d2b60c3c2e63d783c022e2f2b68da2f3f88fcb7"), smt-lemma{}()]
```


With this, the backend seems to work

**Comment by goodlyrottenapple** [comment] 2022-12-09 12:24
ah, but that doesn't seem to actually make it into the solver :/

**Comment by goodlyrottenapple** [comment] 2022-12-09 12:30
ok, this worked, not sure if useful tho?

```

// rule `_andBool_`(`_<=Int_`(`_&Int_`(X,Y),X),`_<=Int_`(`_&Int_`(X,Y),Y))=>#token("true","Bool") requires `_andBool_`(`_<=Int_`(#token("0","Int"),X),`_<=Int_`(#token("0","Int"),Y)) ensures #token("true","Bool") [UNIQUE_ID(fb6b0fd23915d4e80df6751b2d2b60c3c2e63d783c022e2f2b68da2f3f88fcb7), org.kframework.attributes.Location(Location(77,10,79,25)), org.kframework.attributes.Source(Source(/Users/petarmax/Projects/RV/_audits_Ethereum-optimism_optimism/optimism_foundry/optimism-lemmas.k)), org.kframework.definition.Production(syntax #RuleContent ::= #RuleBody "requires" Bool [klabel(#ruleRequires), symbol]), simplification, smt-lemma]
  axiom{R} \implies{R} (
    \equals{SortBool{},R}(
        Lbl'Unds'andBool'Unds'{}(Lbl'Unds-LT-Eqls'Int'Unds'{}(\dv{SortInt{}}("0"),VarX:SortInt{}),Lbl'Unds-LT-Eqls'Int'Unds'{}(\dv{SortInt{}}("0"),VarY:SortInt{})),
        \dv{SortBool{}}("true")),
    \equals{SortBool{},R} (
      Lbl'Unds'andBool'Unds'{}(Lbl'Unds-LT-Eqls'Int'Unds'{}(Lbl'UndsAnd-'Int'Unds'{}(VarX:SortInt{},VarY:SortInt{}),VarX:SortInt{}), Lbl'Unds-LT-Eqls'Int'Unds'{}(Lbl'UndsAnd-'Int'Unds'{}(VarX:SortInt{},VarY:SortInt{}),VarY:SortInt{})),
     \and{SortBool{}} (
       \dv{SortBool{}}("true"),
        \top{SortBool{}}())))
  [org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/Users/petarmax/Projects/RV/_audits_Ethereum-optimism_optimism/optimism_foundry/optimism-lemmas.k)"), org'Stop'kframework'Stop'definition'Stop'Production{}("syntax #RuleContent ::= #RuleBody \"requires\" Bool [klabel(#ruleRequires), symbol]"), org'Stop'kframework'Stop'attributes'Stop'Location{}("Location(77,10,79,25)"), simplification{}(""), UNIQUE'Unds'ID{}("fb6b0fd23915d4e80df6751b2d2b60c3c2e63d783c022e2f2b68da2f3f88fcb7"), smt-lemma{}()]
```

**Comment by PetarMax** [comment] 2022-12-09 12:46
For some reason (updates to the evm semantics possibly), the condition that I need discharged now gets discharged without the `smt-lemma` annotations on the two simplifications. So, the problem is no longer affecting Optimism, but is still there. I don't understand why Z3 is getting stuck (quantifier instantiation loop?), but it seems to be beyond us.

I'd suggest we close this issue, noting that it may arise in the future again somehow.

**Closed** 2022-12-09 12:47 UTC
Labels: investigation, Serokell
