### ISSUE TITLE
Printing K terms in kore-repl

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#1890] opened 2020-06-16 17:03 UTC
`kore-repl` should natively support printing K terms (instead of Kore). The user should be able to pass a command-line option `--kprint "⟨command line⟩"` to `kore-repl`. The frontend can set this option automatically.

**Comment by ttuegel** [comment] 2020-06-16 17:04
This is particularly important as several projects have accumulated sets of aliases to use with `kore-repl`, but this feature should be consolidated.

**Comment by ana-pantilie** [comment] 2022-09-15 11:29
Duplicate of https://github.com/runtimeverification/haskell-backend/issues/2797

**Closed by ana-pantilie** 2022-09-15 11:29 UTC
Labels: feature, kore-repl
