### ISSUE TITLE
Side condition for #Ceil(Set SetItem) should be generated before function evaluations

### ISSUE THREAD

**Issue by denis-bogdanas** [runtimeverification/haskell-backend#3124] opened 2022-06-28 13:18 UTC
Looks like haskell backend first applies function rules, then generates `#Ceil` constraints. This could lead to information loss when result of function evaluation no longer needs `#Ceil` constraints.

Example code: https://github.com/runtimeverification/k/pull/2685
`ceil-order.k`:
```
module CEIL-ORDER
    imports SET
    imports INT
    imports K-EQUAL
    imports BOOL

  syntax KItem ::= step ( Set ) | done ( Set )
  rule <k> step ( Set ) => done ( Set ) </k>

  rule #Ceil(@S:Set SetItem(@E:KItem)) => {(@E in @S) #Equals false} #And #Ceil(@S) #And #Ceil(@E)
    [anywhere, simplification]

  rule (S1 SetItem(E)) -Set S2 =>  S1 -Set S2             requires         E in S2 [simplification]
  rule S1 -Set (S2 SetItem(E)) =>  S1 -Set S2             requires notBool E in S1 [simplification]
endmodule
```
`ceil-order-spec.k`
```
module CEIL-ORDER-SPEC
    imports CEIL-ORDER

  claim <k> step( (S SetItem(X:Int)) -Set SetItem(X) ) => done(S) </k>
endmodule
```

The test passes with current master, but fails with this Haskell backend: https://github.com/runtimeverification/haskell-backend/pull/3062

Failing output:
```
  #Not ( {
    S
  #Equals
    S -Set SetItem ( X:Int )
  } )
#And
  <k>
    done ( S -Set SetItem ( X:Int ) ) ~> .
  </k>
```

Because `#Ceil(S SetItem(X:Int))` was not generated, we miss the side condition `notBool X in S` required to prove the claim.

The test passes if we modify the rules like this, forcing `#Ceil` generation first:
```
  rule (S1 SetItem(E)) -Set S2 =>  S1 -Set S2             requires         E in S2 andBool notBool E in S1 [simplification]
  rule S1 -Set (S2 SetItem(E)) =>  S1 -Set S2             requires notBool E in S1 andBool notBool E in S2 [simplification]
```

**Comment by ana-pantilie** [comment] 2022-06-29 08:40
The two simplification rules are unsound, they should be:

```
  rule (S1 SetItem(E)) -Set S2 =>  S1 -Set S2             requires         E in S2     ensures notBool E in S1 [simplification]
  rule S1 -Set (S2 SetItem(E)) =>  S1 -Set S2             requires notBool E in S1     ensures notBool E in S2 [simplification]
```

The idea is that currently users have to make sure that the definedness of the LHS is preserved on the RHS as well.

**Comment by denis-bogdanas** [comment] 2022-06-29 10:33
That sounds very strange to me. My understanding is that at any time the engine encounters a partially defined functional expression, it should generate `#Ceil` predicates. It would be extraordinary unintuitive and error-prone if besides `#Ceil` rules one have to additionally assert definedness with `ensures` clauses. Is this a bug after all?

@ehildenb what's your thought on this?

**Comment by ana-pantilie** [comment] 2022-06-29 12:12
The backend does generate Ceil predicates for the configuration being rewritten. What I'm saying is that simplification rules apply equational transformations to terms which could invalidate the definedness of a term if users aren't careful enough. We want to make this easier for users in the future, but currently this is the encoding we have for simplification rules.

**Comment by denis-bogdanas** [comment] 2022-06-29 12:31
1. Please confirm if this is a bug.
2. How the rules in my example invalidate definedness? Please explain.

**Comment by ana-pantilie** [comment] 2022-07-05 09:21
@denis-bogdanas If you have `rule (S1 SetItem(E)) -Set S2 =>  S1 -Set S2 requires ...`, the set on the LHS can potentially be undefined if `E in S1`. You need to add that condition to the rule, otherwise, if your configuration has a set like `(SetItem(E) SetItem(E)) -Set SetItem(E)` the simplification rule will rewrite this to `SetItem(E) -Set SetItem(E)`, essentially transforming a `Bottom` configuration into something which is defined.

**Comment by denis-bogdanas** [comment] 2022-07-06 06:24
I got that much. But is this a correct and desired K behavior? You still didn't reply if this is a bug.

**Comment by ana-pantilie** [comment] 2022-07-06 07:44
@denis-bogdanas It's not a bug, this is the current design dictated by the encoding of simplification rules. If we want a different behavior then we'd need to think of a proposal to change the encoding of these rules in a way which would give us the desired features.

**Comment by denis-bogdanas** [comment] 2022-07-06 10:42
Thanks! I already wrote the rules in this manner, but assuming this is a workaround not expected behavior.

@ehildenb What's your opinion of this issue?

**Comment by denis-bogdanas** [comment] 2022-07-06 10:45
Also, if this is expected behavior, then K needs a test for it, to prevent future confusion.

**Comment by ana-pantilie** [comment] 2022-10-05 10:32
Let's add the test to the failing directory of https://github.com/runtimeverification/k/pull/2920/files and close this issue.

**Comment by jberthold** [comment] 2022-10-05 11:24
^^^ The test actually _passes_ on the PR, we can close this as soon as it is merged

**Closed** 2022-10-06 10:16 UTC
Labels: bug, set-simplification
