### ISSUE TITLE
Haskell backend booster returning a doubled substitution

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/haskell-backend#3912] opened 2024-05-31 15:42 UTC
[var-sub.tar.gz](https://github.com/user-attachments/files/15515837/var-sub.tar.gz)

Here, I have an RPC interaction which causes a crash in the Pyk which recieves the module back (assertion error). The assertion error is this one: https://github.com/runtimeverification/k/blob/c82beec7ff95d98eff96d2bfcfe9e77268387c59/pyk/src/pyk/kore/rpc.py#L522. This check is making sure that substitutions passed back only contains one entry per variable in the term. Maybe this just means the haskell backend needs to deduplicate substitution entries which are having the same value? Maybe it's indicative of a deeper bug?

The error I get in pyk is:

```
INFO 2024-05-31 15:34:03,889 pyk.kore.rpc - Received response from localhost:44205: 3 - execute
ERROR 2024-05-31 15:34:03,913 kevm_pyk.utils - Proof crashed: VAT-SLIP-PASS-ROUGH-SPEC.Vat.slip.pass.rough
Duplicate substitution entry key: VarABI'Unds'y : SortInt{}
Traceback (most recent call last):
  File "/home/dev/src/evm-semantics/kevm-pyk/src/kevm_pyk/utils.py", line 237, in run_prover
    strategy.prove(fail_fast=fail_fast, max_iterations=max_iterations, proof=proof)
  File "/home/dev/src/evm-semantics/kevm-pyk/src/kevm_pyk/utils.py", line 173, in prove
    prover.advance_proof(fail_fast=fail_fast, max_iterations=max_iterations, proof=proof)
  File "/home/dev/src/k/pyk/src/pyk/proof/proof.py", line 500, in advance_proof
    results = self.step_proof(step)
  File "/home/dev/src/k/pyk/src/pyk/proof/reachability.py", line 780, in step_proof
    extend_result = self.kcfg_explore.extend_cterm(
  File "/home/dev/src/k/pyk/src/pyk/kcfg/explore.py", line 230, in extend_cterm
    cterm, next_states, depth, vacuous, next_node_logs = self.cterm_symbolic.execute(
  File "/home/dev/src/k/pyk/src/pyk/cterm/symbolic.py", line 133, in execute
    response = self._kore_client.execute(
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 1020, in execute
    return ExecuteResult.from_dict(result)
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 672, in from_dict
    return globals()[ExecuteResult._TYPES[StopReason(dct['reason'])]].from_dict(dct)  # type: ignore
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 767, in from_dict
    next_states=tuple(State.from_dict(next_state) for next_state in dct['next-states']),
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 767, in <genexpr>
    next_states=tuple(State.from_dict(next_state) for next_state in dct['next-states']),
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 496, in from_dict
    State._subst_to_dict(kore_term(dct['rule-substitution'])) if 'rule-substitution' in dct else None
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 522, in _subst_to_dict
    raise ValueError(f'Duplicate substitution entry key: {key.text}')
ValueError: Duplicate substitution entry key: VarABI'Unds'y : SortInt{}
```

**Comment by goodlyrottenapple** [comment] 2024-06-03 09:58
This is coming from the rule-substitution field of the response, which is essentially the raw substitution map returned by the internal matching function. As this is not normalised in anyway, it's perhaps not too surprising this happened. Should be a straightforward fix

**Comment by ehildenb** [comment] 2024-06-11 18:01
@goodlyrottenapple any progress on this? I ran into it again on another proof I'm trying to port off the old `kprove` style prover.

**Comment by ehildenb** [comment] 2024-06-13 19:50
I ran the KEVM proof with this updated version of the Haskell backend, and I'm still getting the same crash.

I'm using K v7.1.3, which contains haskell backend v0.1.10.

I've attached another bug report, but I suspect the original one will do too.

[duplicate-var.tar.gz](https://github.com/user-attachments/files/15827933/duplicate-var.tar.gz)

**Comment by goodlyrottenapple** [comment] 2024-06-13 20:00
Could you please also post the pyk error? I checked that the rpc server no longer generates a duplicate of the `VarABI'Unds'y` from the original bug report before closing, but perhaps there is a different code-path I overlooked which is triggering in the new bug report.

**Comment by PetarMax** [comment] 2024-06-14 08:09
For me, the pyk error is:
```
ERROR 2024-06-14 09:07:53,799 kevm_pyk.utils - Proof crashed: contracts%model%MEscrow.lock(uint256):0
Duplicate substitution entry key: VarCALLER'Unds'ID : SortInt{}
Traceback (most recent call last):
  File "/nix/store/j630cbipwzx87nja89ss84dx6lvn7kfm-python3.10-kevm-pyk-1.0.600/lib/python3.10/site-packages/kevm_pyk/utils.py", line 236, in run_prover
    strategy.prove(fail_fast=fail_fast, max_iterations=max_iterations, proof=proof)
  File "/nix/store/j630cbipwzx87nja89ss84dx6lvn7kfm-python3.10-kevm-pyk-1.0.600/lib/python3.10/site-packages/kevm_pyk/utils.py", line 172, in prove
    prover.advance_proof(fail_fast=fail_fast, max_iterations=max_iterations, proof=proof)
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/proof/proof.py", line 500, in advance_proof
    results = self.step_proof(step)
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/proof/reachability.py", line 789, in step_proof
    extend_result = self.kcfg_explore.extend_cterm(
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/kcfg/explore.py", line 230, in extend_cterm
    cterm, next_states, depth, vacuous, next_node_logs = self.cterm_symbolic.execute(
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/cterm/symbolic.py", line 129, in execute
    response = self._kore_client.execute(
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/kore/rpc.py", line 1020, in execute
    return ExecuteResult.from_dict(result)
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/kore/rpc.py", line 672, in from_dict
    return globals()[ExecuteResult._TYPES[StopReason(dct['reason'])]].from_dict(dct)  # type: ignore
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/kore/rpc.py", line 767, in from_dict
    next_states=tuple(State.from_dict(next_state) for next_state in dct['next-states']),
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/kore/rpc.py", line 767, in <genexpr>
    next_states=tuple(State.from_dict(next_state) for next_state in dct['next-states']),
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/kore/rpc.py", line 496, in from_dict
    State._subst_to_dict(kore_term(dct['rule-substitution'])) if 'rule-substitution' in dct else None
  File "/nix/store/4s9kl9ww30xjicrlw3s7fjmrhw8pqm2x-python3.10-pyk-7.0.127/lib/python3.10/site-packages/pyk/kore/rpc.py", line 522, in _subst_to_dict
    raise ValueError(f'Duplicate substitution entry key: {key.text}')
ValueError: Duplicate substitution entry key: VarCALLER'Unds'ID : SortInt{}

```
but I think your fix hasn't reached Kontrol yet. It is interesting that this error is coming up in two different scenarios right now.

Let me also add my relevant bug report [here](https://github.com/user-attachments/files/15834807/subst.tar.gz)
, with `CALLER_ID` being the duplicate variable. 

I don't quite understand how this could have happened, though, given what substitutions should be - mappings from variables to values. How can even a raw substitution have multiple bindings for the same variable, is that what happened?

**Comment by PetarMax** [comment] 2024-06-14 09:10
I've printed out the substitution that I get, and the relevant part (with some sort info elided) is:
```
Equals(left=EVar(name="VarCALLER'Unds'ID"), right=EVar(name="VarCONTRACT'Unds'ID")), 
Equals(left=EVar(name="VarCALLER'Unds'ID"), right=EVar(name="VarVV0'Unds'from'Unds'114b9705")), 

Equals(left=EVar(name="VarCONTRACT'Unds'ID"), right=App(symbol="Lbl'UndsAnd-'Int'Unds'", sorts=(), args=(DV(value=String(value='1461501637330902918203684832716283019655932542975')), App(symbol='Lbllookup', sorts=(), args=(EVar(name="VarCONTRACT'Unds'STORAGE"), DV(value=String(value='1'))))))), 
Equals(left=EVar(name="VarCONTRACT'Unds'ID"), right=EVar(name="VarVV1'Unds'to'Unds'114b9705")), 
```
The variables on the LHS of these equalities come from *the rule to be applied*, not the current state, and the expressions on the RHS come from the current state. I am assuming that variables prefixed with `_` on the LHS of the entire substitution come from the current state and the `_` is there to distinguish them from the ones from the RHS. 

I will investigate further to see what is in the generated CSE rules that should be applied.

**Comment by PetarMax** [comment] 2024-06-14 10:02
After further inspection, my assumption was wrong, so the previous few comments don't hold.

**Comment by ehildenb** [comment] 2024-06-14 16:54
Using this branch, I get this error:

```
INFO 2024-06-14 16:50:45,129 pyk.kore.rpc - Sending request to localhost:32823: 3 - execute
[proxy] Processing request 3
INFO 2024-06-14 16:50:51,108 pyk.kore.rpc - Received response from localhost:32823: 3 - execute
ERROR 2024-06-14 16:50:51,113 kevm_pyk.utils - Proof crashed: SUM-TO-N-SPEC.loop
Duplicate substitution entry key: VarI : SortInt{} -> ['\\dv{SortInt{}}("0")', '\\dv{SortInt{}}("1")']
Traceback (most recent call last):
  File "/home/dev/src/evm-semantics/kevm-pyk/src/kevm_pyk/utils.py", line 241, in run_prover
    strategy.prove(fail_fast=fail_fast, max_iterations=max_iterations, proof=proof)
  File "/home/dev/src/evm-semantics/kevm-pyk/src/kevm_pyk/utils.py", line 175, in prove
    prover.advance_proof(fail_fast=fail_fast, max_iterations=max_iterations, proof=proof)
  File "/home/dev/src/k/pyk/src/pyk/proof/proof.py", line 502, in advance_proof
    results = self.step_proof(step)
  File "/home/dev/src/k/pyk/src/pyk/proof/reachability.py", line 794, in step_proof
    extend_result = self.kcfg_explore.extend_cterm(
  File "/home/dev/src/k/pyk/src/pyk/kcfg/explore.py", line 230, in extend_cterm
    cterm, next_states, depth, vacuous, next_node_logs = self.cterm_symbolic.execute(
  File "/home/dev/src/k/pyk/src/pyk/cterm/symbolic.py", line 129, in execute
    response = self._kore_client.execute(
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 1020, in execute
    return ExecuteResult.from_dict(result)
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 672, in from_dict
    return globals()[ExecuteResult._TYPES[StopReason(dct['reason'])]].from_dict(dct)  # type: ignore
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 767, in from_dict
    next_states=tuple(State.from_dict(next_state) for next_state in dct['next-states']),
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 767, in <genexpr>
    next_states=tuple(State.from_dict(next_state) for next_state in dct['next-states']),
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 496, in from_dict
    State._subst_to_dict(kore_term(dct['rule-substitution'])) if 'rule-substitution' in dct else None
  File "/home/dev/src/k/pyk/src/pyk/kore/rpc.py", line 522, in _subst_to_dict
    raise ValueError(f'Duplicate substitution entry key: {key.text} -> {[res[key].text, value.text]}')
ValueError: Duplicate substitution entry key: VarI : SortInt{} -> ['\\dv{SortInt{}}("0")', '\\dv{SortInt{}}("1")']
```

**Comment by goodlyrottenapple** [comment] 2024-06-14 17:13
@ehildenb just to confirm, are you getting this error with this branch: https://github.com/runtimeverification/haskell-backend/pull/3939 as well?

**Comment by ehildenb** [comment] 2024-06-14 19:11
@goodlyrottenapple it does seem to be fixed with that one! Thank you!

**Comment by goodlyrottenapple** [comment] 2024-06-14 19:17
Will try to minimise one of these tests and add as integration test on Monday

**Closed** 2024-06-17 12:02 UTC
