### ISSUE TITLE
Missing hook: LIST.range

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/haskell-backend#3706] opened 2023-12-15 17:45 UTC
This is used in the MultiversX semantics

Here is the error message:

```
pyk.kore.rpc.KoreClientError: Runtime error
code= -32002
message= Runtime error
data= {'context': 'CallStack (from HasCallStack):\n  error, called at src/Kore/Rewrite/Function/Evaluator.hs:376:6 in kore-0.60.0.0-70XMVsFZJ088aF7K1Xjfh:Kore.Rewrite.Function.Evaluator', 'error': 'Error: missing hook\nSymbol\n    LblListBytes\'Coln\'range{}\ndeclared with attribute\n    hook{}("LIST.range")\nWe don\'t recognize that hook and it was not given any rules.\nPlease open a feature request at\n    https://github.com/runtimeverification/haskell-backend/issues\nand include the text of this message.\nWorkaround: Give rules for LblListBytes\'Coln\'range{}'}
```

**Comment by jberthold** [comment] 2024-04-17 11:58
Duplicate of #3581

**Closed by jberthold** 2024-04-17 11:58 UTC
